### ISSUE TITLE
`disabled_keys = {}` no longer works as expected

### ISSUE THREAD

**Issue by svanharmelen** [m4xshen/hardtime.nvim#20]
I'm using this config, and I just noticed that `disabled_keys = {}` no longer works as expected. So the key that are disabled by default are still enabled:

<img width="282" alt="image" src="https://github.com/m4xshen/hardtime.nvim/assets/4171547/7b04474a-b571-409c-b608-dbf634e2c67a">

**Comment by svanharmelen** [comment]
Same for `restricted_keys` by the way...

**Comment by m4xshen** [comment]
I just update the mechanism of config, see [explanation](https://img.shields.io/badge/Next-black?style=for-the-badge&logo=next.js&logoColor=white). In your case you should change it to:
```lua
disabled_keys = {
   ["<UP>"] = {},
   ["<DOWN>"] = {},
   ["<LEFT>"] = {},
   ["<RIGHT>"] = {},
},
```

**Comment by svanharmelen** [comment]
The explanation link doesn't seem to work, but I get the picture. Does mean I have to add quite some config now (both in `disabled_keys` and `restricted_keys`) just to prevent getting all the defaults... But at least I have a way to fix my issue so thanks for your reaction!

**Comment by svanharmelen** [comment]
I does work a bit strange/unexpected now through. When I add this (see first screenshot), I still get the other defaults as well. While I get how it works now, this way of configuring the plugin feels a bit weird/unexpected and not inline with how other plugin configs tent to work...

<img width="271" alt="image" src="https://github.com/m4xshen/hardtime.nvim/assets/4171547/09390ca8-8525-4fed-b8ac-a1d8b7ea4bb1">

So to make things work again I now have to add this config instead:

<img width="278" alt="image" src="https://github.com/m4xshen/hardtime.nvim/assets/4171547/14a6f804-4f85-4402-b5d4-12521d8c7ef8">

**Comment by m4xshen** [comment]
Sorry I sent the wrong link, [here is the correct one](https://github.com/m4xshen/hardtime.nvim#-configuration).

The reason why I update the config mechanism is because in the latest update there are a lot of config in [hints](https://github.com/m4xshen/hardtime.nvim/blob/main/lua/hardtime/config.lua#L51) so if users want to add an customize there own hints, they have to copy all the default hints first and then add a new one, which is inefficient. But with the new mechanism, they can just add a new one in their config and remove some of the hints by setting them to `{}`. If you have a better approach to solve this problem feel free to tell me!

**Comment by svanharmelen** [comment]
Thanks for the updated link and I understand that it's a tradeoff (isn't it always 😉). While a little less convenient for me, it's super easy to fix so I'm good.

Thanks for your work on this plugin (it helps me not to cheat 😊 ) and your reactions!
